---
- hosts: web
  name: Apache
  become: yes

  tasks:
    - name: Installing Apache.
      apt:
        name: apache2
        state: present

    - name: Copy Configuration files
      copy:
        src: "{{ item.src}}"
        dest: "{{ item.dest}}"
        owner: root
        group: root
        mode: 0644
      notify:
        - restart apache
        - restart memcache
      with_items:
        - src: index.html
          dest: /var/www/html/index.html
    
    - name: Make sure handlers are flushed immediately.
      meta: flush_handlers

    - name: Ensure If apache is boot up enabled.
      service:
        name: apache2
        state: started
        enabled: true 

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
    - name: restart memcache
      service:
        name: memcached
        state: restarted

    # - name: Copy Configuration files
    #   copy:
    #     src: "{{ item.src}}"
    #     dest: "{{ item.dest}}"
    #     owner: root
    #     group: root
    #     mode: 0644
    #     notify: restart apache
    #   with_items:
    #     - src: index.html
    #       dest: /var/www/html/index.html


    # - name: Ensure If apache is boot up enabled.
    #   service:
    #     name: apache2
    #     state: started
    #     enabled: true
