---
- hosts: web
  name: Apache
  become: yes

  tasks:
    - name: Installing Apache.
      apt:
        name: apache2
        state: present

    - name: Add an Environment variable to the remote users shell
      lineinfile:
        dest: "~/.bash_profile"
        regexp: '^ENV_VAR= '
        line: 'ENV_VAR=value'
      become: false
    - name: get the environment variable
      shell: 'source ~/.bashrc && echo $ENV_VAR'
      register: foo
    - debug: msg="The Variable is {{ foo.stdout }}"
      
    - name: Copy Configuration files
      copy:
        src: "{{ item.src}}"
        dest: "{{ item.dest}}"
        owner: root
        group: root
        mode: 0644
      notify:
        - restart apache
      with_items:
        - src: index.html
          dest: /var/www/html/index.html
    
    - name: Make sure handlers are flushed immediately.
      meta: flush_handlers

    - name: Ensure If apache is boot up enabled.
      service:
        name: apache2
        state: started
        enabled: true 

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted
      notify: restart memcache
    - name: restart memcache
      service:
        name: memcached
        state: restarted

    # - name: Copy Configuration files
    #   copy:
    #     src: "{{ item.src}}"
    #     dest: "{{ item.dest}}"
    #     owner: root
    #     group: root
    #     mode: 0644
    #     notify: restart apache
    #   with_items:
    #     - src: index.html
    #       dest: /var/www/html/index.html


    # - name: Ensure If apache is boot up enabled.
    #   service:
    #     name: apache2
    #     state: started
    #     enabled: true

