---
- hosts: app
  become: true
  
  vars_files:
    - vars.yml

  
  # pre_tasks:
  #   - name: Update yum cache if needed/
  #     yum: 
  #       update_cache: true
  #       cache_valid_time: 3600
  pre_tasks:
    - name: Update yum cache if needed/
      command: yum update -y
  handlers:
    - name: restart solr
      service: name=solr state=restarted

  # tasks:
  #   - name: change config
  #     command: somethinf to change
  #     notify: restart solr
  tasks:
    - name: Install Java
      yum: 
        name:
          - java-1.8.0-openjdk
        state: present

    - name: Downloadling solr
      get_url:
        url: "https://www.apache.org/dyn/closer.lua/lucene/solr/{{ solr_version }}/solr-{{ solr_version }}.tgz?action=download"
        dest: "{{ download_dir }}/solr-{{ solr_version }}.tgz" 
        checksum: "{{ solr_checksum }}" 

    - name: Unarchive
      unarchive:
        src: "{{ download_dir }}/solr-{{ solr_version }}.tgz"
        dest: "{{ download_dir }}"
        remote_src: true
        creates: "{{ download_dir }}/solr-{{ solr_version }}/readme.txt"

    - name: Run Solr installation scripts
      command: >
        {{ download_dir }}/solr-{{ solr_version }}/bin/install_solr_service.sh 
        {{ download_dir }}/solr-{{ solr_version }}.tgz
        -i /opt
        -d /opt/solr
        -u solr
        -s solr
        -p 8983
        creates={{ solr_dir }}/bin/solr
    
    - name: Ensure Solr is started at boot/
      service:
        name: solr
        state: started
        enabled: True
