---
- name: Install Httpd
  hosts: app
  become: True

  tasks:
    - name: Httpd Installing
      yum:
        name:
          - httpd
          - git
        state: present

    # - name: Copy Configuration files
    #   copy:
    #     src: "{{ item.src}}"
    #     dest: "{{ item.dest}}"
    #     owner: root
    #     group: root
    #     mode: 0644
    #   with_items:
    #     - src: httpd.conf
    #       dest: /etc/httpd/conf/httpd.conf
    #     - src: httpd-vhosts.conf
    #       dest: /etc/httpd/conf/httpd-vhosts.conf

    - name: Starting HTTPD 
      service:
        name: httpd
        state: started
        enabled: True
    - name: Copy Configuration files
      copy:
        src: "{{ item.src}}"
        dest: "{{ item.dest}}"
        owner: root
        group: root
        mode: 0644
      with_items:
        - src: index.html
          dest: /var/www/html/index.html
        